---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aynyalia/chakra.aynyalian.my.id/
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .eslintrc.json $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH